export {};

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

// Inline every file in src/assets/ as a base64 data URI into a generated
// src/_assets.ts (gitignored). A plugin bundle runs in QuickJS with no file
// server, so reference art and fonts must ride inside the JS as data URIs.
const MIME: Record<string, string> = {
  ".webp": "image/webp",
  ".png": "image/png",
  ".otf": "font/otf",
  ".ttf": "font/ttf",
};

{
  const dir = join(import.meta.dir, "src/assets");
  const entries: string[] = [];
  for (const name of readdirSync(dir)) {
    const ext = name.slice(name.lastIndexOf("."));
    const mime = MIME[ext];
    if (!mime) continue;
    const b64 = readFileSync(join(dir, name)).toString("base64");
    entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(`data:${mime};base64,${b64}`)},`);
  }
  const out =
    `// GENERATED by build.ts — do not edit. Reference art inlined as data URIs.\n` +
    `export const assets: Record<string, string> = {\n${entries.join("\n")}\n};\n`;
  writeFileSync(join(import.meta.dir, "src/_assets.ts"), out);
  console.log(`inlined ${entries.length} asset(s) -> src/_assets.ts`);
}

const result = await Bun.build({
  entrypoints: ["src/main.tsx"],
  target: "browser",
  format: "iife",
  minify: false,
  define: {
    "process.env.NODE_ENV": '"production"',
  },
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

await Bun.write("build/main.js", await result.outputs[0].text());
console.log("built src/main.tsx -> build/main.js");
