// Shared build step for the example UIs: inline src/assets/ as base64 data
// URIs into a generated src/_assets.ts (gitignored), then bundle src/main.tsx
// with Bun. A plugin bundle runs in QuickJS with no file server, so reference
// art and fonts must ride inside the JS as data URIs.
//
// Each example's build.ts is a thin caller:
//   await buildExampleUi(import.meta.dir);
// with optional hooks for assets that need special handling (see delay).

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const MIME: Record<string, string> = {
  ".webp": "image/webp",
  ".png": "image/png",
  ".otf": "font/otf",
  ".ttf": "font/ttf",
};

export interface BuildExampleUiOptions {
  /** Skip an asset file (it is handled elsewhere, e.g. rides in a manifest). */
  skip?: (name: string) => boolean;
  /** Extra source appended to the generated _assets.ts (extra exports). */
  append?: string;
}

/** Generate src/_assets.ts from src/assets/. Returns the inlined count. */
export function inlineAssets(uiDir: string, opts: BuildExampleUiOptions = {}): number {
  const dir = join(uiDir, "src/assets");
  const entries: string[] = [];
  // An example built from stock components (compressor) has no art at all.
  // Still write the file, so `import { assets }` resolves either way.
  for (const name of existsSync(dir) ? readdirSync(dir) : []) {
    if (name.includes(".tmp.")) continue; // prep-time intermediates, never ship
    if (opts.skip?.(name)) continue;
    const ext = name.slice(name.lastIndexOf("."));
    const mime = MIME[ext];
    if (!mime) continue;
    const b64 = readFileSync(join(dir, name)).toString("base64");
    entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(`data:${mime};base64,${b64}`)},`);
  }
  const out =
    `// GENERATED by build.ts — do not edit. Reference art inlined as data URIs.\n` +
    `export const assets: Record<string, string> = {\n${entries.join("\n")}\n};\n` +
    (opts.append ? `\n${opts.append}` : "");
  writeFileSync(join(uiDir, "src/_assets.ts"), out);
  console.log(`inlined ${entries.length} asset(s) -> src/_assets.ts`);
  return entries.length;
}

/** Inline assets, then bundle src/main.tsx -> build/main.js. */
export async function buildExampleUi(uiDir: string, opts: BuildExampleUiOptions = {}): Promise<void> {
  inlineAssets(uiDir, opts);

  const result = await Bun.build({
    entrypoints: [join(uiDir, "src/main.tsx")],
    target: "browser",
    format: "iife",
    minify: false,
    sourcemap: "external",
    define: {
      "process.env.NODE_ENV": '"production"',
    },
  });

  if (!result.success) {
    for (const log of result.logs) console.error(log);
    process.exit(1);
  }

  const bundle = result.outputs.find((o) => o.kind === "entry-point") ?? result.outputs[0];
  const mapArtifact = result.outputs.find((o) => o.kind === "sourcemap");
  let text = await bundle.text();

  // Prepend the source map as ONE line so error stacks translate back to
  // src/*.tsx (see runtime's __vsreact_mapStack). Prepended — not appended —
  // because an error thrown during initial evaluation must already have it;
  // being exactly one line makes the line offset a constant 1.
  if (mapArtifact !== undefined) {
    const full = JSON.parse(await mapArtifact.text());
    // Line mapping needs sources + mappings only; sourcesContent embeds every
    // original file and would double the bundle.
    const map = { version: full.version, sources: full.sources, mappings: full.mappings };
    const holder = JSON.stringify({ file: "main.js", lineOffset: 1, map });
    text = `globalThis.__vsreact_sourcemap = ${holder};\n${text}`;
  }

  await Bun.write(join(uiDir, "build/main.js"), text);
  console.log(`built src/main.tsx -> build/main.js${mapArtifact !== undefined ? " (+sourcemap)" : ""}`);
}
