export {};

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

// Inline every image in src/assets/ as a base64 data URI into a generated
// src/_assets.ts (gitignored). A plugin bundle runs in QuickJS with no file
// server, so reference art must ride inside the JS as data URIs.
//
// The knob film-strip's manifest (knob-strip.json, produced by
// bakeKnobStrip.ts) is also read here and emitted as `knobStrip` so main.tsx
// gets {size, frames, sweepDegrees, dataUri} without a runtime JSON import.
// We take the strip's data URI straight from the manifest (it already carries
// the lossless base64) and skip re-inlining knob-strip.webp as a raw asset.
const MIME: Record<string, string> = {
  ".webp": "image/webp",
  ".png": "image/png",
  ".otf": "font/otf",
  ".ttf": "font/ttf",
};

{
  const dir = join(import.meta.dir, "src/assets");
  const entries: string[] = [];
  for (const name of readdirSync(dir)) {
    if (name === "knob-strip.webp") continue; // rides inside the manifest below
    const ext = name.slice(name.lastIndexOf("."));
    const mime = MIME[ext];
    if (!mime) continue;
    const b64 = readFileSync(join(dir, name)).toString("base64");
    entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(`data:${mime};base64,${b64}`)},`);
  }

  const manifestPath = join(dir, "knob-strip.json");
  if (!existsSync(manifestPath)) {
    console.error(
      "missing src/assets/knob-strip.json — run:\n" +
        "  bun run ../../js/src/tools/bakeKnobStrip.ts <thisDir>/src/assets 90 180",
    );
    process.exit(1);
  }
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
    size: number;
    frames: number;
    sweepDegrees: number;
    dataUri: string;
  };

  const out =
    `// GENERATED by build.ts — do not edit. Reference art inlined as data URIs.\n` +
    `export const assets: Record<string, string> = {\n${entries.join("\n")}\n};\n\n` +
    `export const knobStrip = {\n` +
    `  size: ${manifest.size},\n` +
    `  frames: ${manifest.frames},\n` +
    `  sweepDegrees: ${manifest.sweepDegrees},\n` +
    `  dataUri: ${JSON.stringify(manifest.dataUri)},\n` +
    `} as const;\n`;
  writeFileSync(join(import.meta.dir, "src/_assets.ts"), out);
  console.log(
    `inlined ${entries.length} asset(s) + knob-strip (${manifest.frames} frames @ ${manifest.size}px) -> src/_assets.ts`,
  );
}

const result = await Bun.build({
  entrypoints: ["src/main.tsx"],
  target: "browser",
  format: "iife",
  minify: false,
  define: {
    "process.env.NODE_ENV": '"production"',
  },
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

await Bun.write("build/main.js", await result.outputs[0].text());
console.log("built src/main.tsx -> build/main.js");
